export const arcana = ["major", "minor"]

export const majors = [
  ["fool", "The Fool"],
  ["magician", "The Magician"],
  ["priestess", "The High Priestess"],
  ["empress", "The Empress"],
  ["emperor", "The Emperor"],
  ["hierophant", "The Hierophant"],
  ["lovers", "The Lovers"],
  ["chariot", "The Chariot"],
  ["strength", "Strength"],
  ["hermit", "The Hermit"],
  ["wheel", "Wheel of Fortune"],
  ["justice", "Justice"],
  ["hanged", "The Hanged Man"],
  ["death", "Death"],
  ["temperance", "Temperance"],
  ["devil", "The Devil"],
  ["tower", "The Tower"],
  ["star", "The Star"],
  ["moon", "The Moon"],
  ["sun", "The Sun"],
  ["judgement", "Judgement"],
  ["world", "The World"],
]

export const suits = [
  ["wand", "baton", "rod", "staff", "acorn", "clover", "club"],
  ["cup", "goblet", "rose", "heart"],
  ["sword", "shield", "leaf", "pike", "spade"],
  ["pentacle", "coin", "disk", "bell", "tile", "diamond"],
]

export const pips = {
  1: ["ace", "one"],
  2: ["two"],
  3: ["three"],
  4: ["four"],
  5: ["five"],
  6: ["six"],
  7: ["seven"],
  8: ["eight"],
  9: ["nine"],
  10: ["ten"],
  11: ["page", "jack", "knave"],
  12: ["knight", "cavalier"],
  13: ["queen", "lady"],
  14: ["king"],
}

export const numerals = {
  0: "o",
  1: "i",
  2: "ii",
  3: "iii",
  4: "iv",
  5: "v",
  6: "vi",
  7: "vii",
  8: "viii",
  9: "ix",
  10: "x",
  11: "xi",
  12: "xii",
  13: "xiii",
  14: "xiv",
  15: "xv",
  16: "xvi",
  17: "xvii",
  18: "xviii",
  19: "xix",
  20: "xx",
  21: "xxi",
}
