export const cards = {
  "Fool": {
    arcanum: "major",
    handle: "Fool",
    index: 0,
    name: "The Fool",
    num: 0,
    suit: "",
  },
  "Magician": {
    arcanum: "major",
    handle: "Magician",
    index: 1,
    name: "The Magician",
    num: 1,
    suit: "",
  },
  "HighPriestess": {
    arcanum: "major",
    handle: "HighPriestess",
    index: 2,
    name: "The High Priestess",
    num: 2,
    suit: "",
  },
  "Empress": {
    arcanum: "major",
    handle: "Empress",
    index: 3,
    name: "The Empress",
    num: 3,
    suit: "",
  },
  "Emperor": {
    arcanum: "major",
    handle: "Emperor",
    index: 4,
    name: "The Emperor",
    num: 4,
    suit: "",
  },
  "Hierophant": {
    arcanum: "major",
    handle: "Hierophant",
    index: 5,
    name: "The Hierophant",
    num: 5,
    suit: "",
  },
  "Lovers": {
    arcanum: "major",
    handle: "Lovers",
    index: 6,
    name: "The Lovers",
    num: 6,
    suit: "",
  },
  "Chariot": {
    arcanum: "major",
    handle: "Chariot",
    index: 7,
    name: "The Chariot",
    num: 7,
    suit: "",
  },
  "Strength": {
    arcanum: "major",
    handle: "Strength",
    index: 8,
    name: "Strength",
    num: 8,
    suit: "",
  },
  "Hermit": {
    arcanum: "major",
    handle: "Hermit",
    index: 9,
    name: "The Hermit",
    num: 9,
    suit: "",
  },
  "WheelFortune": {
    arcanum: "major",
    handle: "WheelFortune",
    index: 10,
    name: "Wheel of Fortune",
    num: 10,
    suit: "",
  },
  "Justice": {
    arcanum: "major",
    handle: "Justice",
    index: 11,
    name: "Justice",
    num: 11,
    suit: "",
  },
  "HangedMan": {
    arcanum: "major",
    handle: "HangedMan",
    index: 12,
    name: "The HangedMan",
    num: 12,
    suit: "",
  },
  "Death": {
    arcanum: "major",
    handle: "Death",
    index: 13,
    name: "The Death",
    num: 13,
    suit: "",
  },
  "Temperance": {
    arcanum: "major",
    handle: "Temperance",
    index: 14,
    name: "Temperance",
    num: 14,
    suit: "",
  },
  "Devil": {
    arcanum: "major",
    handle: "Devil",
    index: 15,
    name: "The Devil",
    num: 15,
    suit: "",
  },
  "Tower": {
    arcanum: "major",
    handle: "Tower",
    index: 16,
    name: "The Tower",
    num: 16,
    suit: "",
  },
  "Star": {
    arcanum: "major",
    handle: "Star",
    index: 17,
    name: "The Star",
    num: 17,
    suit: "",
  },
  "Moon": {
    arcanum: "major",
    handle: "Moon",
    index: 18,
    name: "The Moon",
    num: 18,
    suit: "",
  },
  "Sun": {
    arcanum: "major",
    handle: "Sun",
    index: 19,
    name: "The Sun",
    num: 19,
    suit: "",
  },
  "Judgement": {
    arcanum: "major",
    handle: "Judgement",
    index: 20,
    name: "The Devil",
    num: 20,
    suit: "",
  },
  "World": {
    arcanum: "major",
    handle: "World",
    index: 21,
    name: "The World",
    num: 21,
    suit: "",
  },
}
